version: "3.2"

services:

  php_game_score:
    container_name: php_game_score
    build:
      context: './php/'
    ports:
      - "9000:9000"
    volumes:
      - ./back:/var/www/sf
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini-production

  nginx_game_score:
    container_name: nginx_game_score
    image: nginx:stable-alpine
    ports:
      - "88:80"
    volumes:
      - ./back:/var/www/sf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_game_score

  ui_game_score:
    container_name: ui_game_score
    build:
      context: './front'
    ports:
      - "3001:3000"    
    volumes:
      - "/app/node_modules"
      - ./front:/app

  mysql_game_score:
    container_name: mysql_game_score
    image: mysql/mysql-server #M1 compatbibl
    ports:
      - "33060:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_ROOT_HOST: '%'

  phpmyadmin:
    container_name: phpmyadmin_game_score
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql_game_score
      PMA_USER: root
      PMA_PASSWORD: pwd
    ports:
      - "8098:80"
