version: "3.2"

services:

  mysql_game_score2:  
    container_name: mysql_game_score2
    image: mysql/mysql-server #M1 compatbibl
    ports:
      - "33060:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql 

  ui_game_score2:
    container_name: ui_game_score2
    build:
      context: './front'
    ports:
      - "3001:3000"    
    volumes:
      - "/app/node_modules"
      - ./front:/app
  
  phpmyadmin:
    container_name: phpmyadmin_game_score2
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql_game_score2
      PMA_USER: root
      PMA_PASSWORD: pwd
    ports:
      - "8098:80"

  php_game_score2:
    container_name: php_game_score2
    build:
      context: './back/'
    ports:
      - "9000:9000"
    volumes:
      - ./back:/var/www/sf

  nginx_game_score2:
    container_name: nginx_game_score2
    image: nginx:stable-alpine
    ports:
      - "88:80"
    volumes:
      - ./back:/var/www/sf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_game_score2